### ISSUE TITLE
添加SakuraFrp穿透服务地址

### ISSUE THREAD

**Issue by PYmili** [hite4044/Minecraft-Server-Ports-Scanner-GUI#4]
# SakuraFrp服务

希望添加SakuraFrp的地址扫描。

[SakuraFrp官网](www.natfrp.com)

---

### 添加原因

SakuraFrp也是很多内网穿透方案选择之一，可以添加进去。

#### vars.py

```python
servers: List[str] = [
    "frp-man.top", # SakuraFrp Server Address
    "s2.wemc.cc",  # 220.198.120.151
    "cn-yw-plc-1.openfrp.top",  # 122.242.149.92
    "ningbo-3689d402.of-7af93c01.shop",
    "cn-hz-bgp-1.of-7af93c01.shop",
    "cn-hk-bgp-4.openfrp.top",  # 191.96.240.164
    "ganzhou-eb7c59a5.of-7af93c01.shop",
    "cn-he-plc-2.of-7af93c01.shop",
    "cn-bj-plc-2.of-7af93c01.shop",
    "shenzhen-a8bf9282.of-7af93c01.shop",
    "ipyingshe.com",  # 111.45.28.82
    "xiaomy.net",  # 112.16.229.54
    "yuming.net",  # 118.139.160.68
    "dongtaiyuming.net",  # 203.107.44.133
    'chiyu.red',
    'dx.wdsj.net',
    'hiaxn.cn',
    'kazer.team',
    'lolita.bgp.originera.cn',
    'lt.wdsj.net',
    'magicalserver.tpddns.cn',
    'magicmc.cn',
    'mc.163mc.cn',
    'mc.ariacraft.net',
    'mc.kilor.cn',
    'mc.remiaft.com',
    'mc20.rhymc.com',
    'mc3.rhymc.com',
    'mcyc.win',
    'mhxj.club',
    'play.cloudegg.cloud',
    'play.simpfun.cn',
    'sa1.mc164.cn',
    'server.hpnetwork.top'
]
```
![temp](https://github.com/hite4044/Minecraft-Server-Ports-Scanner-GUI/assets/87461263/d479c688-ccc7-444e-b2ad-dda08e864eaf)

**Comment by hite4044** [comment]
WOC，扫描SakuraFrp服务器会被封禁IP的，你快去解封一下：
IP获取：https://iplark.com/
IP解封：https://www.natfrp.com/tunnel/ip-ban
亲身经历，不信你试试域名还ping不ping得通

![image](https://github.com/hite4044/Minecraft-Server-Ports-Scanner-GUI/assets/129571243/4c5530df-b83b-4b0d-8da6-427649335b67)

**Comment by PYmili** [comment]
![image](https://github.com/hite4044/Minecraft-Server-Ports-Scanner-GUI/assets/87461263/597bd817-4ce8-4b33-942f-d9a4e96cfc3a)
我这里一切正常啊？
![Uploading image.png…]()

**Comment by PYmili** [comment]
![image](https://github.com/hite4044/Minecraft-Server-Ports-Scanner-GUI/assets/87461263/d1970498-6dbd-4436-96b5-824f80d495c6)

**Comment by hite4044** [comment]
修了下无法检测SakuraFrp域名的Bug，我刚才试了下，扫得出来，但是我之前用旧的工具扫会封禁
༼ つ ◕_◕ ༽つ

**Comment by PYmili** [comment]
我注意到需要扫描的地址，在用户输入后无法自动缓存，我准备将这个功能补上，后面可以提交一个pr。

**Comment by hite4044** [comment]
@PYmili 
艹！，你再试试？？！
![image](https://github.com/hite4044/Minecraft-Server-Ports-Scanner-GUI/assets/129571243/0cf482cf-8cea-4e38-a714-e81767c8d7a4)

**Comment by hite4044** [comment]
没了啦，都是你害的辣
@PYmili

**Comment by hite4044** [comment]
现在你肯定ping不通了

**Comment by PYmili** [comment]
![image](https://github.com/hite4044/Minecraft-Server-Ports-Scanner-GUI/assets/87461263/63598d3c-4d2a-4344-b0e4-bef0d08cfda0)
依然正常，我准备在做其他扫描方式对服务器进行扫描。我们加一下联系方式

**Comment by hite4044** [comment]
@PYmili 
QQ：695663633
看到请回复删除评论

**Comment by PYmili** [comment]
OK了
