### ISSUE TITLE
運行時出現錯誤

### ISSUE THREAD

**Issue by Paul-16098** [hite4044/Minecraft-Server-Ports-Scanner-GUI#6]
運行時出現錯誤:
![image](https://github.com/hite4044/Minecraft-Server-Ports-Scanner-GUI/assets/127955132/06f963a8-8eac-4074-9f05-ca5e09bc9c36)
使用命令行可打開
```run.bat
chcp 65001
echo off
cls
"mc服务器扫描器3.0.exe"
pause
```
但是沒有掃描按鈕:
![image](https://github.com/hite4044/Minecraft-Server-Ports-Scanner-GUI/assets/127955132/fef588c4-8b46-40e9-909f-8a7e543ad12d)
命令行輸出:
```cmd_log
GUI构建时间: 0.129秒
Done! Found main window, use: 354.76 ms, hWnd: 396142
```

**Comment by hite4044** [comment]
已经修复第二个问题，请下载最新版本来解决

**Comment by hite4044** [comment]
已修复第一个问题，请下载最新版本Releases-0.0.6
