### ISSUE TITLE
交流群

### ISSUE THREAD

**Issue by 185050399** [hite4044/Minecraft-Server-Ports-Scanner-GUI#7]
q群无法搜索 希望可以新建一个telegram或者discord的交流群

**Comment by hite4044** [comment]
抱歉，我不计划添加这些交流群，我不习惯使用这些软件。
其次我将在README.md里增加Q群名：`MCSPS交流群`

**Comment by 185050399** [comment]
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: hite4044 ***@***.***>
发送时间: Saturday, May 4, 2024 1:21:49 PM
收件人: hite4044/Minecraft-Server-Ports-Scanner-GUI ***@***.***>
抄送: 185050399 ***@***.***>; Author ***@***.***>
主题: Re: [hite4044/Minecraft-Server-Ports-Scanner-GUI] 交流群 (Issue #7)


抱歉，我不计划添加这些交流群，我不习惯使用这些软件。
其次我将在README.md里增加Q群名：MCSPS交流群

―
